### ISSUE TITLE
Empty Javadoc JAR for v6.10 in JFrog BinTray

### ISSUE THREAD

**Issue by madphysicist** [cbeust/testng#1273]
### Expected behavior
https://dl.bintray.com/cbeust/maven/org/testng/testng/6.10/testng-6.10-javadoc.jar is expected to contain a valid Javadoc repository for TestNG

### Actual behavior
The JAR file is empty of any documentation. It contains only a `META-INF` folder which contains only a single `MANIFEST.MF` file, which contains only a single Windows-style newline.

### Is the issue reproductible on runner?
N/A

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Go to website, open jar file as zip.

**Comment by madphysicist** [comment]
Any plans to regenerate this file? I ask because I am maintaining the documentation package for TestNG in the Arch User Repository and getting it directly from the pre-built version is much easier than building from scratch as I have been doing.

**Comment by krmahadevan** [comment]
@madphysicist - The javadocs are available for 6.10 in maven central.
Wouldn't that work for you ?

http://repo1.maven.org/maven2/org/testng/testng/6.9.10/

**Comment by madphysicist** [comment]
@krmahadevan Unfortunately "testng-6.10-javadoc.jar" under http://repo1.maven.org/maven2/org/testng/testng/6.10/ appears to be the same 166-byte nearly-empty file, but thanks for pointing me to that site.

**Comment by krmahadevan** [comment]
@madphysicist - I see the following 
```
testng-6.9.10-javadoc.jar                          2015-12-15 16:55              1370397
```
In http://repo1.maven.org/maven2/org/testng/testng/6.9.10/

Can you please check once again ?

**Comment by juherr** [comment]
Same issue for me with http://repo1.maven.org/maven2/org/testng/testng/6.10/ 

```
testng-6.10-javadoc.jar                            2016-12-06 14:06                  166
```

**Comment by juherr** [comment]
@cbeust Something looks wrong in the release script

@madphysicist 

> Any plans to regenerate this file?

No, because it is not possible to override files on maven central.
We will try to fix it in the next release.

**Comment by madphysicist** [comment]
@juherr Makes sense. Thanks for looking into it.

**Comment by cbeust** [comment]
Yes, I'm aware of the problem.

Note that it's possible to override files on JCenter, but not Maven Central.

**Comment by cbeust** [comment]
I fixed testng-6.10-javadoc.jar on JCenter:

http://jcenter.bintray.com/org/testng/testng/6.10/

**Comment by madphysicist** [comment]
Thanks.

**Comment by madphysicist** [comment]
By the way, this issue still appears to be in: effect for 6.14.3:

- https://dl.bintray.com/cbeust/maven/org/testng/testng/6.14.3/testng-6.14.3-javadoc.jar
- http://jcenter.bintray.com/org/testng/testng/6.14.3/:testng-6.14.3-javadoc.jar
- http://repo1.maven.org/maven2/org/testng/testng/6.14.3/testng-6.14.3-javadoc.jar

        testng-6.14.3-javadoc.jar                         2018-04-09 16:44       256 

All the repos listed have the same effectively-empty file.

**Comment by madphysicist** [comment]
Is it worth reopening the issue?

**Comment by juherr** [comment]
@madphysicist It is already tracked with #1628

**Comment by madphysicist** [comment]
@juherr Thanks for pointing me to the other ticket. Are there instructions somewhere on how to build just the documentation? I will am modifying my PKGBUILD file to build the docs from scratch, but if I could avoid building everything else, that would be great.

**Comment by juherr** [comment]
@madphysicist `./gradlew javadoc` should generate the javadoc.
