### ISSUE TITLE
6.9.7 Required JDK 8

### ISSUE THREAD

**Issue by dr29bart** [cbeust/testng#822]
IDEA or Eclipse fails to launch tests on JDK 1.7:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/testng/remote/RemoteTestNG : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by cbeust** [comment]
Just deployed 6.9.8 to JCenter, which should fix this problem.

**Comment by juherr** [comment]
Available on [maven central](http://search.maven.org/#artifactdetails%7Corg.testng%7Ctestng%7C6.9.8%7Cjar) too.

I will reopen the issue if 6.9.8 doesn't fix your problem.

**Comment by dr29bart** [comment]
Verified. The issue is gone.
